### PR TITLE
Expand slugs to allow UUIDs to be used.

### PR DESCRIPTION
**Pull request by msporny**
Please review to see if we want to allow UUIDs to be used for sysSlugs via the HTTP API.

### CODE REVIEW

**Comment by dlongley** [comment]
LGTM. @davidlehn -- did we have any good reasons for requiring slugs to start with a letter?

**Comment by davidlehn** [comment]
I don't recall if there was a reason for starting with a letter.

**Comment by msporny** [comment]
This change broke the tests, updating tests now.

**Comment by msporny** [comment]
@mattcollier @davidlehn Do I need to do anything now to bump the major version? Or do we do that after the PR is pulled into master?

**Pull request merged**
